jwt_pub_key = "./conf/public.pem"
database_url = "postgres://app:!ChangeMe!@database/app"

[app]
name = "app"
env = "dev"
debug = true

[log]
level = "debug"
format = "compact"

[server]
addr = "0.0.0.0"
port = 3000
workers = 4
