#!/usr/bin/env bash
##
## Description:
##   Setup the locoal development environment. This will create the necessary PEM
##   files to create and validate JWT tokens, as well as generate a JWT token to
##   be used for testing and development.
##
## Usage:
##   dev-setup
##

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Generate RSA public/private keys
${__dir}/jwt.sh -o conf key

echo -e "\n"

# Output JWT token to `jwt.txt` and echo to the console
${__dir}/jwt.sh -e 172800 new user@example.com ./keys/private.pem > jwt.txt
cat jwt.txt
