#!/usr/bin/env bash
##
## Description:
##   Create the private and public PEM keys to be used for generating and validating
##   JWT tokens. This should only be used for local development.
##
## Usage:
##   mk-rsa-keys
##

ssh-keygen -t rsa -P "" -b 4096 -m PEM -f private.pem

rm private.pem.pub

openssl rsa -in private.pem -pubout -outform PEM -out public.pem
