apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-dynamic-env
type: Opaque
data:
  {{- range $key, $value := .Values.server.secretsEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end -}}
