apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rws.fullname" . }}
  labels:
    {{- include "rws.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=13&charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  jwt_public_key: {{ .Values.server.secretsFile.JWT_PUBLIC_KEY_FILE }}

